#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gspell-soname1
Version  : 1.6.1
Release  : 9
URL      : https://download.gnome.org/sources/gspell/1.6/gspell-1.6.1.tar.xz
Source0  : https://download.gnome.org/sources/gspell/1.6/gspell-1.6.1.tar.xz
Summary  : Spell checking for GTK+
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-gspell-soname1-bin = %{version}-%{release}
Requires: compat-gspell-soname1-data = %{version}-%{release}
Requires: compat-gspell-soname1-lib = %{version}-%{release}
Requires: compat-gspell-soname1-license = %{version}-%{release}
Requires: compat-gspell-soname1-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libc6-locale
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(enchant)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : vala
BuildRequires : valgrind

%description
gspell - a spell-checking library for GTK+ applications
=======================================================

%package bin
Summary: bin components for the compat-gspell-soname1 package.
Group: Binaries
Requires: compat-gspell-soname1-data = %{version}-%{release}
Requires: compat-gspell-soname1-license = %{version}-%{release}

%description bin
bin components for the compat-gspell-soname1 package.


%package data
Summary: data components for the compat-gspell-soname1 package.
Group: Data

%description data
data components for the compat-gspell-soname1 package.


%package dev
Summary: dev components for the compat-gspell-soname1 package.
Group: Development
Requires: compat-gspell-soname1-lib = %{version}-%{release}
Requires: compat-gspell-soname1-bin = %{version}-%{release}
Requires: compat-gspell-soname1-data = %{version}-%{release}
Provides: compat-gspell-soname1-devel = %{version}-%{release}
Requires: compat-gspell-soname1 = %{version}-%{release}

%description dev
dev components for the compat-gspell-soname1 package.


%package doc
Summary: doc components for the compat-gspell-soname1 package.
Group: Documentation

%description doc
doc components for the compat-gspell-soname1 package.


%package lib
Summary: lib components for the compat-gspell-soname1 package.
Group: Libraries
Requires: compat-gspell-soname1-data = %{version}-%{release}
Requires: compat-gspell-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-gspell-soname1 package.


%package license
Summary: license components for the compat-gspell-soname1 package.
Group: Default

%description license
license components for the compat-gspell-soname1 package.


%package locales
Summary: locales components for the compat-gspell-soname1 package.
Group: Default

%description locales
locales components for the compat-gspell-soname1 package.


%prep
%setup -q -n gspell-1.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552401125
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1552401125
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-gspell-soname1
cp COPYING %{buildroot}/usr/share/package-licenses/compat-gspell-soname1/COPYING
%make_install
%find_lang gspell-1

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/gspell-app1

%files data
%defattr(-,root,root,-)
%exclude /usr/lib64/girepository-1.0/Gspell-1.typelib
%exclude /usr/share/gir-1.0/Gspell-1.gir

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/gspell-1/gspell/gspell-checker-dialog.h
%exclude /usr/include/gspell-1/gspell/gspell-checker.h
%exclude /usr/include/gspell-1/gspell/gspell-entry-buffer.h
%exclude /usr/include/gspell-1/gspell/gspell-entry.h
%exclude /usr/include/gspell-1/gspell/gspell-enum-types.h
%exclude /usr/include/gspell-1/gspell/gspell-language-chooser-button.h
%exclude /usr/include/gspell-1/gspell/gspell-language-chooser-dialog.h
%exclude /usr/include/gspell-1/gspell/gspell-language-chooser.h
%exclude /usr/include/gspell-1/gspell/gspell-language.h
%exclude /usr/include/gspell-1/gspell/gspell-navigator-text-view.h
%exclude /usr/include/gspell-1/gspell/gspell-navigator.h
%exclude /usr/include/gspell-1/gspell/gspell-text-buffer.h
%exclude /usr/include/gspell-1/gspell/gspell-text-view.h
%exclude /usr/include/gspell-1/gspell/gspell-version.h
%exclude /usr/include/gspell-1/gspell/gspell.h
%exclude /usr/lib64/libgspell-1.so
%exclude /usr/lib64/pkgconfig/gspell-1.pc

%files doc
%defattr(0644,root,root,0755)
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellChecker.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellCheckerDialog.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellEntry.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellEntryBuffer.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellLanguage.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellLanguageChooser.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellLanguageChooserButton.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellLanguageChooserDialog.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellNavigator.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellNavigatorTextView.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellTextBuffer.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GspellTextView.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GtkEntry-support.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/GtkTextView-support.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/annexes.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/annotation-glossary.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/api-index-full.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/api-reference.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/core-classes.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/gspell-1.0.devhelp2
%exclude /usr/share/gtk-doc/html/gspell-1.0/home.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/index.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/intro.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/language-choosers.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/left-insensitive.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/left.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/object-tree.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/right-insensitive.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/right.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/spell-checker-dialog.html
%exclude /usr/share/gtk-doc/html/gspell-1.0/style.css
%exclude /usr/share/gtk-doc/html/gspell-1.0/up-insensitive.png
%exclude /usr/share/gtk-doc/html/gspell-1.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgspell-1.so.1
/usr/lib64/libgspell-1.so.1.3.0

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-gspell-soname1/COPYING

%files locales -f gspell-1.lang
%defattr(-,root,root,-)

